pipelines:
  default:
    - step:
        script:
          - apt-get update -y && apt-get install wget
          - apt-get -y install git
          - wget https://github.com/gohugoio/hugo/releases/download/v0.22.1/hugo_0.22.1_Linux-64bit.deb
          - dpkg -i hugo*.deb
          - git submodule update --init
          - git clone --depth 1 git@github.com:iamjay/iamjay.github.io.git public
          - (cd public && git rm -rf *)
          - hugo
          - git config --global user.email "pathompong@gmail.com"
          - git config --global user.name "Pathompong Puengrostham"
          - (cd public && git add -A && git commit -m "Deploy from bitbucket" && git push)
