baseURL = "https://www.jayjournal.net"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Jay's Journal"
theme = "hugo-tranquilpeak-theme"
disqusShortname = "jayjournal"
googleAnalytics = "UA-102582424-1"

[permalinks]
    post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[author]
    name = "Jay's Journal"
    bio = "Technology • Travel • Family • Life"
    location = "Bangkok - Thailand"
    picture = "/css/images/logo.png"
    #gravatarEmail = "pathompong@gmail.com"

# Menu Configuration
[[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
    url = "/"
[[menu.main]]
    weight = 2
    identifier = "categories"
    name = "Categories"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
    url = "/categories"
[[menu.main]]
    weight = 3
    identifier = "tags"
    name = "Tags"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
    url = "/tags"
[[menu.links]]
    weight = 4
    identifier = "facebook"
    name = "Facebook"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-facebook\"></i>"
    url = "https://www.facebook.com/jayjournal.net"
[[menu.misc]]
    weight = 5
    identifier = "rss"
    name = "RSS"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
    url = "/index.xml"

[params]
    date_format = "2 January 2006"
    clearReading = false
    description = "Hugo tranquilpeak theme demo"
    sidebarBehavior = 1
    coverImage = "https://source.unsplash.com/8zMIksrTrOQ/1600x900"
    imageGallery = true
    thumbnailImage = true
    autoThumbnailImage = true
    favicon = "/favicon.ico"
    keywords = [ "pantip", "ท่องเที่ยว", "เที่ยวด้วยตัวเอง" ]

[params.sidebar.profile]
    url = "/"

[params.footer]
    copyright = "pathompong@gmail.com"

[blackfriday]
    hrefTargetBlank = true
